# Generated by Django 4.2 on 2023-04-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_column='_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userpassword',
            field=models.CharField(max_length=100),
        ),
    ]
