# Generated by Django 2.2.28 on 2023-04-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_maker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='createdBy',
            field=models.CharField(default='000000', max_length=50),
        ),
    ]
